version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:latest
    ports:
      - "9080:9080"
    #volumes:
    #  - ./var/log:/var/log:ro
    command: -config.file=/etc/promtail/config.yml -log.level=debug
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./var/grafana:/var/lib/grafana    
    networks:
      - loki